version: '3.1'

services:
  web:
    image: nginx:latest
    container_name: web_album
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d


    # 宿主机执行（解决403 forbidden）
    #chmod -R 755 ./html/images
    #chown -R 101:101 ./html/images  # Nginx容器默认用户UID=101
    
